// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rooms.proto

/*
Package main is a generated protocol buffer package.

It is generated from these files:
	rooms.proto

It has these top-level messages:
	Session
	Mess
	Nothing
*/
package main

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Session struct {
	Login string `protobuf:"bytes,1,opt,name=login" json:"login,omitempty"`
	Room  string `protobuf:"bytes,2,opt,name=room" json:"room,omitempty"`
}

func (m *Session) Reset()                    { *m = Session{} }
func (m *Session) String() string            { return proto.CompactTextString(m) }
func (*Session) ProtoMessage()               {}
func (*Session) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Session) GetLogin() string {
	if m != nil {
		return m.Login
	}
	return ""
}

func (m *Session) GetRoom() string {
	if m != nil {
		return m.Room
	}
	return ""
}

type Mess struct {
	Mess string `protobuf:"bytes,1,opt,name=mess" json:"mess,omitempty"`
}

func (m *Mess) Reset()                    { *m = Mess{} }
func (m *Mess) String() string            { return proto.CompactTextString(m) }
func (*Mess) ProtoMessage()               {}
func (*Mess) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Mess) GetMess() string {
	if m != nil {
		return m.Mess
	}
	return ""
}

type Nothing struct {
	Dummy bool `protobuf:"varint,1,opt,name=dummy" json:"dummy,omitempty"`
}

func (m *Nothing) Reset()                    { *m = Nothing{} }
func (m *Nothing) String() string            { return proto.CompactTextString(m) }
func (*Nothing) ProtoMessage()               {}
func (*Nothing) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Nothing) GetDummy() bool {
	if m != nil {
		return m.Dummy
	}
	return false
}

func init() {
	proto.RegisterType((*Session)(nil), "main.Session")
	proto.RegisterType((*Mess)(nil), "main.Mess")
	proto.RegisterType((*Nothing)(nil), "main.Nothing")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for RS service

type RSClient interface {
	Subscribe(ctx context.Context, in *Nothing, opts ...grpc.CallOption) (*Mess, error)
	Publish(ctx context.Context, opts ...grpc.CallOption) (RS_PublishClient, error)
}

type rSClient struct {
	cc *grpc.ClientConn
}

func NewRSClient(cc *grpc.ClientConn) RSClient {
	return &rSClient{cc}
}

func (c *rSClient) Subscribe(ctx context.Context, in *Nothing, opts ...grpc.CallOption) (*Mess, error) {
	out := new(Mess)
	err := grpc.Invoke(ctx, "/main.RS/Subscribe", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rSClient) Publish(ctx context.Context, opts ...grpc.CallOption) (RS_PublishClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_RS_serviceDesc.Streams[0], c.cc, "/main.RS/Publish", opts...)
	if err != nil {
		return nil, err
	}
	x := &rSPublishClient{stream}
	return x, nil
}

type RS_PublishClient interface {
	Send(*Mess) error
	Recv() (*Mess, error)
	grpc.ClientStream
}

type rSPublishClient struct {
	grpc.ClientStream
}

func (x *rSPublishClient) Send(m *Mess) error {
	return x.ClientStream.SendMsg(m)
}

func (x *rSPublishClient) Recv() (*Mess, error) {
	m := new(Mess)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for RS service

type RSServer interface {
	Subscribe(context.Context, *Nothing) (*Mess, error)
	Publish(RS_PublishServer) error
}

func RegisterRSServer(s *grpc.Server, srv RSServer) {
	s.RegisterService(&_RS_serviceDesc, srv)
}

func _RS_Subscribe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Nothing)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RSServer).Subscribe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/main.RS/Subscribe",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RSServer).Subscribe(ctx, req.(*Nothing))
	}
	return interceptor(ctx, in, info, handler)
}

func _RS_Publish_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RSServer).Publish(&rSPublishServer{stream})
}

type RS_PublishServer interface {
	Send(*Mess) error
	Recv() (*Mess, error)
	grpc.ServerStream
}

type rSPublishServer struct {
	grpc.ServerStream
}

func (x *rSPublishServer) Send(m *Mess) error {
	return x.ServerStream.SendMsg(m)
}

func (x *rSPublishServer) Recv() (*Mess, error) {
	m := new(Mess)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _RS_serviceDesc = grpc.ServiceDesc{
	ServiceName: "main.RS",
	HandlerType: (*RSServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Subscribe",
			Handler:    _RS_Subscribe_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Publish",
			Handler:       _RS_Publish_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "rooms.proto",
}

func init() { proto.RegisterFile("rooms.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 223 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0x41, 0x4b, 0xc3, 0x40,
	0x10, 0x85, 0xdd, 0x12, 0x8d, 0x1d, 0x11, 0x61, 0xf1, 0x50, 0xea, 0x41, 0xc9, 0xc5, 0x9c, 0x96,
	0x62, 0xff, 0x41, 0x2f, 0x9e, 0x94, 0x90, 0x1c, 0x3c, 0x37, 0xed, 0x90, 0x0e, 0x64, 0x33, 0x61,
	0x27, 0x0b, 0xfa, 0xef, 0x65, 0x36, 0x39, 0xe8, 0xed, 0x7b, 0xfb, 0xf6, 0xcd, 0x0c, 0x0f, 0xee,
	0x02, 0xb3, 0x17, 0x37, 0x06, 0x9e, 0xd8, 0x66, 0xfe, 0x48, 0x43, 0xb1, 0x87, 0xbc, 0x41, 0x11,
	0xe2, 0xc1, 0x3e, 0xc2, 0x75, 0xcf, 0x1d, 0x0d, 0x1b, 0xf3, 0x62, 0xca, 0x75, 0x3d, 0x0b, 0x6b,
	0x21, 0xd3, 0xd4, 0x66, 0x95, 0x1e, 0x13, 0x17, 0x5b, 0xc8, 0x3e, 0x50, 0x44, 0x3d, 0x8f, 0x22,
	0x4b, 0x20, 0x71, 0xf1, 0x0c, 0xf9, 0x27, 0x4f, 0x17, 0x1a, 0x3a, 0x1d, 0x78, 0x8e, 0xde, 0xff,
	0x24, 0xff, 0xb6, 0x9e, 0xc5, 0xdb, 0x17, 0xac, 0xea, 0xc6, 0x96, 0xb0, 0x6e, 0x62, 0x2b, 0xa7,
	0x40, 0x2d, 0xda, 0x7b, 0xa7, 0xb7, 0xb8, 0x25, 0xb7, 0x85, 0x59, 0xea, 0x8a, 0xe2, 0xca, 0xbe,
	0x42, 0x5e, 0xc5, 0xb6, 0x27, 0xb9, 0xd8, 0x3f, 0xc6, 0xff, 0x4f, 0xa5, 0xd9, 0x99, 0xc3, 0x0e,
	0x9e, 0x88, 0x5d, 0x17, 0xc6, 0x93, 0xc3, 0xef, 0xa3, 0x1f, 0x7b, 0x14, 0x17, 0x38, 0x4e, 0xd8,
	0x45, 0x3a, 0xe3, 0xe1, 0xa1, 0x56, 0x7e, 0x57, 0xae, 0xb4, 0x80, 0xca, 0xb4, 0x37, 0xa9, 0x89,
	0xfd, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xeb, 0x42, 0xd7, 0xf1, 0x18, 0x01, 0x00, 0x00,
}
